# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "63be868871ff844a26f66004cd9b4316"
name = "Checkout Call Recovery AI"
application_url = "https://checkout-call-recovery-ai.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks/checkouts/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_orders,write_products,read_checkouts"



[auth]
redirect_urls = [ "https://checkout-call-recovery-ai.onrender.com/api/auth" ]
